/*=========================================================================
 *
 *  Copyright NumFOCUS
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/

// This file has been generated by BuildHeaderTest.py
// To regenerate, build the ITKHeaderTests target.
// This is a test to include each header file for Insight.

#include "itkIndexValuePair.h"
#include "itkPhaseImageToImageFilter.h"
#include "itkPhaseExamplesImageSource.h"
#include "itkHelmholtzDecompositionImageFilter.h"
#include "itkWrapPhaseFunctor.h"
#include "itkWrappedPhaseDifferencesBaseImageFilter.h"
#include "itkItohPhaseUnwrappingImageFilter.h"
#include "itkDCTImageFilter.h"
#include "itkQualityGuidedPhaseUnwrappingImageFilter.h"
#include "itkPhaseQualityImageFilter.h"
#include "itkWrapPhaseImageFilter.h"
#include "itkDCTPoissonSolverImageFilter.h"
#include "itkDCTPhaseUnwrappingImageFilter.h"
#include "itkPhaseDerivativeVarianceImageFilter.h"
#include "itkPhaseResidueImageFilter.h"
#include "itkWrappedPhaseLaplacianImageFilter.h"

#include <cstdlib> // needed for EXIT_SUCCESS macro

int main ( int , char* [] )
{

  return EXIT_SUCCESS;
}
