#!/bin/sh

# Convenience script for running SWIG before it is installed.
# Intended for ad-hoc usage and not by the test-suite or examples.

builddir=`dirname "$0"`
SWIG_LIB='/home/mahran/build/Wrapping/Generators/SwigInterface/swig-prefix/src/swig/Lib'
export SWIG_LIB
exec "$builddir/swig" "$@"
